### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 586124. Received 2181128

### ISSUE THREAD

**Issue by Bas950** [sapics/ip-location-api#1]
```
ILA_FIELDS=latitude,longitude
```

Use your example IP from README

```ts
lookup("207.97.227.239")
```

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 586124. Received 2181128
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readInt32LE (node:internal/buffer:392:5)
    at setCityRecord (<redacted>/node_modules/.pnpm/ip-location-api@1.0.0_debug@4.3.7/node_modules/ip-location-api/src/main.mjs:319:29)
    at lookup (<redacted>/node_modules/.pnpm/ip-location-api@1.0.0_debug@4.3.7/node_modules/ip-location-api/src/main.mjs:75:9)
    at index (<redacted>/apps/api-master/src/index.ts:22:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_OUT_OF_RANGE'
}
```

**Comment by Bas950** [comment]
FYI: don't forget to run updateDb
